[metadata]
  name = "basic"

[global]
  plan = "libp2p/ping"
  case = "ping"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.build_config]
go_proxy_mode = "remote"
go_proxy_url = "https://goproxy.io"


[[groups]]
  id = "regular"
  instances = { count = 2 }

