name = "network"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "ping-pong"
instances = { min = 2, max = 2, default = 2 }

# seq 1
[[testcases]]
name = "traffic-allowed"
instances = { min = 1, max = 1, default = 1 }

# seq 2
[[testcases]]
name = "traffic-blocked"
instances = { min = 1, max = 1, default = 1 }
