[metadata]
  name = "network"

[global]
  plan = "examples/network"
  case = "ping-pong"
  total_instances = 2
  builder = "docker:go"
  runner = "cluster:k8s"

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

# [global.run.test_params]
# size      = "1MB"
# count     = "1000"

[[groups]]
  id = "simple"
  instances = { count = 2 }
  [groups.resources]
    memory = "512Mi"
    cpu = "500m"

# [[groups]]
#   id = "requestors"
#   instances = { count = 4 }
#   [groups.resources]
#     memory = "4096Mi"
#     cpu = "1000m"
