name: Run Ping Pong (example) Workflow
on:
  workflow_call:
    inputs:
      testground_endpoint:
        description: testground_endpoint
        required: false
        type: string
      testground_runner:
        description: testground_runner
        required: true
        default: 'local:docker'
        type: string
      collect_name:
        description: collect_name
        required: true
        type: string
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: setup testground
        uses: ./.github/actions/setup-testground
        with:
          testground_endpoint: ${{ inputs.testground_endpoint }}


      - name: run the test
        shell: bash
        id: run
        run: |
          testground plan import --from ./examples --name examples;
            
          if [ "${{ inputs.testground_runner }}" == "cluster:k8s" ]; then
            testground run composition -f ./examples/network/ping-pong.k8s.toml | tee run.out
          else
            # TODO: For some reason healthcheck on k8s doesn't work:
            # invalid character '<' looking for beginning of value
            # Error: Process completed with exit code 1.
            testground healthcheck --runner ${{ inputs.testground_runner }} --fix
            testground run composition -f ./examples/network/ping-pong.ci.toml | tee run.out
          fi

          ./check_result.sh;

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
      #   timeout-minutes: 3

      - name: Collect test ouputs
        shell: bash
        if: ${{ steps.run.outputs.testground_id && (success() || failure()) }}
        run: |
          testground collect \
            --runner=${{ inputs.testground_runner }} \
            --output ~/testground_output.tgz \
            "${{ steps.run.outputs.testground_id }}"

      - uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: ${{ inputs.collect_name }}
          path: |
            ~/testground_output.tgz
            ~/daemon.out

